theme: jekyll-theme-slate
title: Universal Game/Genetic Engine
description: An Exploration on linking the Game Universe with the Business Universe through Never Ending Genetic Algorithms
logo: [logo.png]
